### PR TITLE
Shawn Whitefield Assignment 2

### PR DESCRIPTION
**Pull request by swhitefi**
Thanks for the  help!

### CODE REVIEW

**Comment by pschloss** [comment]
Shawn,
Good start, but could you see the email I just sent out with the clarification on how I'd like stuff formatted?
Pat

**Comment by swhitefi** [comment]
Ok thanks! I think I have fixed all of the formatting now.
should I submit a new pull request?

**Comment by pschloss** [comment]
Looks good, thanks.

**Comment by pschloss** [comment]
good job

**Pull request closed without merging**
