### PR TITLE
Schmidt Finished assignment02

### PR DESCRIPTION
**Pull request by marschmi**
Is this the type of document you're looking for?

### CODE REVIEW

**Comment by pschloss** [comment]
I’m actually looking for something more like what I had in the example where the output is embedded in the text. So for the first one you have:

How many samples were described in the wild.metadata.txt?
length(unique(row.names(metadata)))

What I’d rather see is:

How many samples were described in the wild.metadata.txt?
nsamples <- length(unique(row.names(metadata)))

There are `r nsamples` samples in the `wild.metadata.txt` file.

Make sense?
Pat

On Sep 18, 2014, at 4:05 PM, marschmi notifications@github.com wrote:

> Is this the type of document you're looking for?
> 
> You can merge this Pull Request by running
> 
>   git pull https://github.com/marschmi/assignment02 master
> Or view, comment on, or merge it at:
> 
>   https://github.com/microbialinformatics/assignment02/pull/2
> 
> Commit Summary
> 
> Finished assignment02
> File Changes
> 
> M .gitignore (1)
> M README.Rmd (50)
> M README.md (130)
> A Schmidt_HW2.Rmd (165)
> A Schmidt_HW2.md (340)
> A assignment02.Rproj (13)
> A metadata_exludes_Ear&Repro.csv (112)
> Patch Links:
> 
> https://github.com/microbialinformatics/assignment02/pull/2.patch
> https://github.com/microbialinformatics/assignment02/pull/2.diff
> —
> Reply to this email directly or view it on GitHub.

## 

Department of Microbiology & Immunology
University of Michigan
1520A Medical Science Research Bldg. I
1150 West Medical Center Dr.
Ann Arbor, MI 48109-0620
734.647.5801 (office)
734.936.2951 (lab)
734.764.3562 (fax)
Twitter: @PatSchloss
http://www.med.umich.edu/microbio/bio/schloss.htm
http://www.mothur.org

#

**Comment by marschmi** [comment]
Hi Pat,

I see the problem.  On my assignment02 page, the README.md file is the
original one I had done before you sent us the details.  I then changed the
name of the file to "Schmidt_HW2.md/.rdm", which you can see if you click
one of those files.  Once you click on the Schmidt_HW2.rmd file, it looks
like this:

 [image: Inline image 1]

I will change the README.md file to reflect the Schmdit_HW2.md file.
~Marian

**Comment by marschmi** [comment]
Hi Pat, 
I changed the README.md and it should reflect the changes that I had made to address your comments.  Sorry for the confusion.
Thanks for the help,
~Marian

**Comment by pschloss** [comment]
great - thanks

On Sep 19, 2014, at 10:28 AM, marschmi notifications@github.com wrote:

> Hi Pat, 
> I changed the README.md and it should reflect the changes that I had made to address your comments. Sorry for the confusion.
> Thanks for the help,
> ~Marian
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Department of Microbiology & Immunology
University of Michigan
1520A Medical Science Research Bldg. I
1150 West Medical Center Dr.
Ann Arbor, MI 48109-0620
734.647.5801 (office)
734.936.2951 (lab)
734.764.3562 (fax)
Twitter: @PatSchloss
http://www.med.umich.edu/microbio/bio/schloss.htm
http://www.mothur.org

#

**Comment by pschloss** [comment]
1. You gave the number of female PMG instead of the number of female PL
2. For the metadata with two conditions there are two &'s and there should only be one

**Pull request closed without merging**
